'use client'; //??

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import React, { useState } from 'react';

import Profile from './components/mainPage/profile'
import Topbanner from './components/mainPage/topbanner'
import Midbanner from './components/mainPage/midbanner'
import VideoBanner from './components/mainPage/videobanner'
import Bottombanner from './components/mainPage/bottombanner'
import Comments from './components/mainPage/comments'
import Footer from './components/mainPage/footer'
import Registration from './components/registerationPage/registration';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const [showRegistration, setShowRegistration] = useState(false);

  return (
    <html lang="en">
      <body>
        <Profile onButtonClick={() => setShowRegistration(true)} />
        <Topbanner />
        <Registration />
        {/* {showRegistration ? <Registration /> : <Midbanner />} */}
        <VideoBanner />
        <Bottombanner />
        <Comments />
        <Footer />
        {children}
      </body>
    </html>
  );
}
